import { chromium } from '../.cache/cta-check/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const context = await browser.newContext();
let requests = 0;
await context.route(/https:\/\/[^/]*(googletagmanager|google-analytics)\.com\//, async route => { requests++; await route.fulfill({ contentType: 'application/javascript', body: '' }); });
await context.route('**/rest/v1/patient_reviews*', route => route.fulfill({ contentType: 'application/json', body: '[]' }));
const page = await context.newPage();
const origin = 'http://127.0.0.1:5181';
const eventCount = () => page.evaluate(() => (window.dataLayer || []).filter(entry => entry[0] === 'event').length);
try {
  await page.goto(origin + '/services/colonoscopy-lower-gi-endoscopy?email=private@example.com#private');
  await page.getByRole('button', { name: 'Reject Non-Essential', exact: true }).waitFor();
  await page.evaluate(async () => { const analytics = await import('/src/lib/analytics.ts'); analytics.trackEvent('contact_form_submit'); });
  assert.equal(requests, 0); assert.equal(await eventCount(), 0);
  await page.getByRole('button', { name: 'Accept All', exact: true }).click();
  await page.waitForFunction(() => document.getElementById('osec-ga'));
  await page.evaluate(async () => { const analytics = await import('/src/lib/analytics.ts'); analytics.trackEvent('contact_form_submit'); });
  const commands = await page.evaluate(() => (window.dataLayer || []).map(entry => Array.from(entry)));
  const data = JSON.stringify(commands);
  assert.ok(!data.includes('private@example.com')); assert.ok(!data.includes('colonoscopy')); assert.ok(!data.includes('#private'));
  assert.ok(commands.some(entry => entry[0] === 'event' && entry[1] === 'service_view'));
  assert.ok(commands.some(entry => entry[0] === 'config' && entry[2].send_page_view === false && entry[2].allow_google_signals === false));
  await page.evaluate(() => document.cookie = '_ga=qa;path=/');
  await page.locator('footer').getByRole('button', { name: 'Cookie Preferences' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Reject Non-Essential' }).click();
  const before = await eventCount();
  await page.evaluate(async () => { const analytics = await import('/src/lib/analytics.ts'); analytics.trackEvent('contact_form_submit'); analytics.trackPageView(); });
  assert.equal(await eventCount(), before);
  assert.equal(await page.evaluate(() => document.cookie.includes('_ga=')), false);
  assert.equal(await page.evaluate(() => window['ga-disable-G-TESTONLY']), true);
  await page.evaluate(() => localStorage.setItem('osec-cookie-consent', JSON.stringify({ version: 1, essential: true, analytics: true, savedAt: Date.now() - 181 * 86400000 })));
  const beforeReload = requests;
  await page.reload(); await page.getByRole('heading', { name: 'Your cookie choices' }).waitFor();
  assert.equal(requests, beforeReload);
  console.log('PASS no pre-consent events, no sensitive URLs, explicit event whitelist, withdrawal blocks events, cookie deletion, expired consent');
  const denied = await browser.newContext();
  await denied.route(/https:\/\/[^/]*(googletagmanager|google-analytics)\.com\//, route => route.abort());
  await denied.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('Blocked', 'SecurityError'); }; Storage.prototype.getItem = () => { throw new DOMException('Blocked', 'SecurityError'); }; });
  const blocked = await denied.newPage(); await blocked.goto(origin + '/cookie-policy');
  await blocked.getByRole('button', { name: 'Reject Non-Essential', exact: true }).click();
  await blocked.getByRole('status').waitFor();
  assert.equal(await blocked.locator('.osec-cookies--banner').count(), 0);
  console.log('PASS graceful blocked browser storage');
  await denied.close();
} finally { await browser.close(); }
